### PR TITLE
[splash] Update Splash Page Content 

### PR DESCRIPTION
**Pull request by stacyk**
delaney-dawson-BXs8SjVelKs-unsplash

## Trello:
https://trello.com/c/jgfmdWDp/88-i-want-content-for-the-splash-welcome-page-telling-me-what-metashare-is#

Prototype: https://xd.adobe.com/view/83a1d44c-230d-4db4-62db-02343fdc33ac-f590/

  - [x] Needs static images of screenshots

### CODE REVIEW

**Comment by stacyk** [comment]
[I want content for the splash/welcome page telling me what MetaShare is.](https://trello.com/c/jgfmdWDp/88-i-want-content-for-the-splash-welcome-page-telling-me-what-metashare-is)

**Comment by jgerigmeyer** [comment]
Not a big deal, but might be easier to read at iPhone size if the `li` text did not wrap below the icons.

Screenshot 2020-01-31 11 27 06

**Comment by stacyk** [comment]
> Looks great. I'm curious if we could zoom in on the screenshots more - maybe have them bleed off the page? They are very small for me at almost every screen size.

@mirisuzanne I don't think we want to (yet). These screenshots are already out of date and fake. Maybe once we get a more finish product with real users we can get better screenshots?

**Comment by jgerigmeyer** [comment]
@stacyk I'm not clear on the status here. Are you saying you think we should go ahead and merge, and worry about updating the screenshots later? Are you planning to change the way the text wraps around the icons, or just not worry about it?

**Pull request merged**
