### PR TITLE
[not-latest-commit] 🛢 Add commits list to ScratchOrg

### PR DESCRIPTION
**Pull request by wlonk**
We expect this to be equal to the commits in the associated Task for the most part, but if someone commits to a task outside of MetaShare, they can diverge, in which case we'll want to show that the ScratchOrg is behind.

cat

### CODE REVIEW

**Comment by wlonk** [comment]
[I want to know if the latest commit my QA org was created from is not the latest/HEAD commit on the task branch.](https://trello.com/c/cJOAFupK/87-i-want-to-know-if-the-latest-commit-my-qa-org-was-created-from-is-not-the-latest-head-commit-on-the-task-branch)

**Comment by jgerigmeyer** [comment]
@wlonk This seems a bit redundant. We already track the `latest_commit` on a ScratchOrg, and the list of `commits` on a Task. Wouldn't it suffice to just compare `scratch_org.latest_commit == scratch_org.task.commits[0]`? What is the additional value of tracking the entire list of commits on an Org?

**Comment by jgerigmeyer** [comment]
[When following a link to a QA org, I want an additional warning if my org is out of date.](https://trello.com/c/3H4uO9tc/92-when-following-a-link-to-a-qa-org-i-want-an-additional-warning-if-my-org-is-out-of-date)

**Comment by wlonk** [comment]
@jgerigmeyer absolutely none value! So that means that this feature had no API changes necessary, and I think we can scrap this PR.

**Pull request closed without merging**
