### PR TITLE
[allow-proper-branch-names] 🛢 Use appropriate validator for branches

### PR DESCRIPTION
**Pull request by wlonk**
cat

### CODE REVIEW

**Comment by wlonk** [comment]
[Bug: Project/Task branch_name fields use SlugField with invalid characters.](https://trello.com/c/SnVAPOhf/115-bug-project-task-branchname-fields-use-slugfield-with-invalid-characters)

**Comment by wlonk** [comment]
Not yet because Docker decided to fall down and I'm rebuilding things. I'll see where that's coming from shortly.

**Comment by wlonk** [comment]
@davisagli we could, but I felt that a name that communicated what kind of field this was (à la how `SlugField` does so) would be more felicitous. I'm not attached to it, but I do think it's a nicer way of doing it.

**Comment by davisagli** [comment]
@wlonk I think it makes it harder to read the model code and understand it. I know from experience how a CharField works; I don't know how a BranchField works without digging around to find the code. That's exacerbated by moving the defaults for max_length, null, and blank to the field class instead of the line where the field is instantiated.

In addition to the readability concerns, I also have concerns that a custom field class will require more work to maintain over time. I think that extra work is warranted for cases where we're actually storing a different type (JSONField, TextField) but I'm not seeing any big payoff for it here.

**Comment by wlonk** [comment]
@davisagli that's enough to convince me. I will change it.

**Pull request merged**
